name: project_vet

services:
  project_vet_front_end:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_vet_front_end
    restart: always
    ports:
      - '5113:80'
    networks:
      - project_vet_network

networks:
  project_vet_network:
    external: true
    name: project_vet_network
