-- AlterEnum
ALTER TYPE "PetSpecies" ADD VALUE 'BIRD';
ALTER TYPE "PetSpecies" ADD VALUE 'RABBIT';
ALTER TYPE "PetSpecies" ADD VALUE 'RODENT';
ALTER TYPE "PetSpecies" ADD VALUE 'FERRET';
ALTER TYPE "PetSpecies" ADD VALUE 'REPTILE';
ALTER TYPE "PetSpecies" ADD VALUE 'FISH';
